-- MySQL Script generated by MySQL Workbench
-- 06/22/15 00:22:57
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mwas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mwas` ;
CREATE SCHEMA IF NOT EXISTS `mwas` DEFAULT CHARACTER SET utf8 ;
USE `mwas` ;

-- -----------------------------------------------------
-- Table `mwas`.`boot_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwas`.`boot_log` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestampUtc` BIGINT(19) UNSIGNED NOT NULL,
  `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
